version: '3'

services:
  users-service:
    build: ./users-service/
    ports:
      - 8081:8081
    env_file:
      - ./users-service/resources/local.env
  products-orders-service:
    build: ./products-orders-service/
    ports:
      - 8080:8080
    env_file:
      - ./products-orders-service/resources/local.env
    depends_on:
      - users-service