version: '3'

services:
  users-service:
    build: ./users-service/
    ports:
      - 8081:8081
    env_file:
      - ./envs/env-users-service.env
  products-orders-service:
    build: ./products-orders-service/
    ports:
      - 8080:8080
    env_file:
      - ./envs/env-products-orders-service.env
    depends_on:
      - users-service
  payments-service:
    build: ./payments-service/
    ports:
      - 8083:8083
    env_file:
      - ./envs/env-payments-service.env
  notifications-service:
    build: ./notifications-service/
    ports:
      - 8000:8000
    env_file:
      - ./envs/env-notifications-service.env
    depends_on:
      - users-service
  order-orchestrator:
    build: ./order-orchestrator/
    ports:
      - 8082:8082
    env_file:
      - ./envs/env-order-orchestrator.env
    depends_on:
      - users-service
      - products-orders-service
      - notifications-service
      - payments-service
