version: '3'

services:
  users-service:
    build: ./users-service/
    ports:
      - 8081:8081
    env_file:
      - ./users-service/resources/local.env
  products-orders-service:
    build: ./products-orders-service/
    ports:
      - 8080:8080
    env_file:
      - ./products-orders-service/resources/local.env
    depends_on:
      - users-service
  payment-service:
    build: ./payment-service/
    ports:
      - 8088:8088
    env_file:
      - ./payment-service/resources/local.env
  notification-service:
    build: ./notification-service/
    ports:
      - 8089:8089
    env_file:
      - ./notification-service/resources/local.env
  order-orchestrator:
    build: ./order-orchestrator/
    ports:
      - 8082:8082
    env_file:
      - ./order-orchestrator/resources/local.env
    depends_on:
      - users-service
      - products-orders-service
      - payment-service
      - notification-service