version: '3'

services:
  users-service:
    build: ./users-service/
    ports:
      - 8081:8081
    env_file:
      - ./env/env-users-service.env
  products-orders-service:
    build: ./products-orders-service/
    ports:
      - 8080:8080
    env_file:
      - ./env/env-products-orders-service.env
    depends_on:
      - users-service
  order-orchestrator:
    build: ./order-orchestrator/
    ports:
      - 8082:8082
    env_file:
      - ./env/env-order-orchestrator.env
    depends_on:
      - users-service
      - products-orders-service
